# costmap_common_params.yaml --- 
# 
# Filename: costmap_common_params.yaml
# Description: Global parameters for layered costmap
# Created: Mon Nov 17 23:52:34 2014 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:
robot_radius: 0.16

# costmap_2d plugins declaration. Order matters!
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer, type: "squirrel_navigation::ObstaclesLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

# Parameters for squirrel_navigation::ObstacleLayer
obstacles_layer:
  obstacle_range: 1.5
  raytrace_range: 3.0 
  observation_sources: laser_scan rgbd_scan
  rgbd_scan: {sensor_frame: kinect_depth_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: false}
  laser_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: false} 
  publish_voxel_map: true
  robot_height: 0.47
  floor_threshold: 0.04
  obstacles_persistence: 30.0

#
# costmap_common_params.yaml ends here
