# costmap_common_params.yaml --- 
# 
# Filename: costmap_common_params.yaml
# Description: Global parameters for layered costmap
# Created: Mon Nov 17 23:52:34 2014 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

# costmap_2d plugins declaration. Order matters!
plugins:
  - {name: map_layer, type: "squirrel_navigation::MapLayer"}
  - {name: platform_layer, type: "squirrel_navigation::ObstaclesLayer"}
  - {name: tower_layer, type: "squirrel_navigation::ObstaclesLayer"}

map_layer:
  robot_link_radis: 0.22
  inflation_radius: 0.6
  cost_scaling_factor: 10.0
  
platform_layer:
  obstacle_range: 1.5
  raytrace_range: 3.0 
  observation_sources: laser_scan rgbd_scan
  rgbd_scan: {sensor_frame: kinect_rgb_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: false}
  laser_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: false} 
  publish_voxel_map: false
  robot_link_radius: 0.22
  max_obstacle_height: 0.25
  min_obstacle_height: 0.03
  obstacles_persistence: 30.0
  inflation_radius: 0.6
  cost_scaling_factor: 10.0

tower_layer:
  obstacle_range: 1.5
  raytrace_range: 3.0 
  observation_sources: rgbd_scan
  rgbd_scan: {sensor_frame: kinect_rgb_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: false}
  publish_voxel_map: false
  robot_link_radius: 0.07
  max_obstacle_height: 0.76
  min_obstacle_height: 0.25
  obstacles_persistence: 30.0
  inflation_radius: 0.3
  cost_scaling_factor: 10.0

#
# costmap_common_params.yaml ends here