robot_radius: 0.22

plugins: # order matters
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer, type: "squirrel_navigation::ObstaclesLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  obstacle_range: 1.5
  raytrace_range: 3.0 
  observation_sources: rgbd_scan laser_scan
  rgbd_scan: {sensor_frame: camera_rgb_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: true}
  laser_scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true} 
  publish_voxel_map: true
  robot_height: 0.76
  floor_threshold: 0.03

inflation_layer: 
  inflation_radius: 0.6
  cost_scaling_factor: 20.0  
