# costmap_common_params.yaml --- 
# 
# Filename: costmap_common_params.yaml
# Description: Global parameters for layered costmap
# Created: Thu Feb 26 18:02:16 2015 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

robot_radius: 0.16

# robot_radius: 0.05 # smallest radius in the stack

# costmap_2d plugins declaration.
plugins:
  - {name: map_layer, type: "squirrel_navigation::MapLayer"}
  - {name: obstacles_layer, type: "squirrel_navigation::DownprojectionLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

map_layer:
  robot_link_radius: 0.22
  inflation_radius: 0.6
  cost_scaling_factor: 10.0

# Parameters for squirrel_navigation::DownprojectionLayer
obstacles_layer:
  obstacle_range: 1.5
  raytrace_range: 3.0 
  observation_sources: laser_scan rgbd_scan
  rgbd_scan: {sensor_frame: kinect_depth_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: false}
  laser_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: false} 
  publish_voxel_map: false
  robot_height: 0.52
  floor_threshold: 0.04
  obstacles_persistence: 30.0

# Parameters for costmap_2d::InflationLayer
inflation_layer:
   inflation_radius: 0.6
   inscribed_radius: 0.18
   cost_scaling_factor: 10

# Parameters for squirrel_navigation::DownprojectionMultilayer
# perception_layer:
#  obstacle_range: 1.5
#  raytrace_range: 3.0
#  observation_sources: rgbd_scan laser_scan
#  laser_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: false} 
#  rgbd_scan: {sensor_frame: kinect_depth_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: false}
#  publish_voxel_map: false
#  num_layers: 2
#  robot_link_radii: "0.22, 0.07"
#  layers_levels: "0.02, 0.26" 
#  max_obstacle_height: 0.52
#  min_obstacle_height: 0.03
#  obstacles_persistence: 20.0
#  inflation_radii: "0.6, 0.3"
#  cost_scaling_factors: "10.0, 10.0"
#  inscribed_radii: "0.18, 0.05"

#
# costmap_common_params.yaml ends here
