global_costmap: {
  global_frame: /map,
  robot_base_frame: /base_link,
  update_frequency: 5.0,
  static_map: true,
  static_layer/enabled: true,
  ostacles_layer/enabled: true,
  inflation_layer/enabled: true}
