# global_costmap_params.yaml --- 
# 
# Filename: global_costmap_params.yaml
# Description: Costmap parameters for the global Planner (Dijkstra)
# Created: Mon Nov 17 23:54:20 2014 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

global_costmap: {
  robot_radius: 0.16,
  global_frame: /map,
  robot_base_frame: /base_link,
  update_frequency: 5.0,
  static_map: true,
  static_layer/enabled: true,
  ostacles_layer/enabled: true,
  inflation_layer/enabled: true,
  inflation_layer/inflation_radius: 0.6,
  inflation_layer/cost_scaling_factor: 10.0}

#
# global_costmap_params.yaml ends here
