# global_costmap_params.yaml --- 
# 
# Filename: global_costmap_params.yaml
# Description: Costmap parameters for the global Planner (Dijkstra)
# Created: Mon Nov 17 23:54:20 2014 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

global_costmap: {
  global_frame: /map,
  robot_base_frame: /base_link,
  update_frequency: 5.0,
  static_map: true,
  static_layer/enabled: true,
  obstacles_layer/enabled: true,
}

#
# global_costmap_params.yaml ends here
