# local_costmap_params.yaml --- 
# 
# Filename: local_costmap_params.yaml
# Description: Costmap parameters for LocalPlanner
# Created: Mon Nov 17 23:54:44 2014 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

local_costmap: {
  global_frame: /map,
  robot_base_frame: /base_link,
  update_frequency: 5.0,
  publish_frequency: 5.0,
  static_map: false,
  resolution: 0.05,
  static_layer/enabled: false,
  obstacles_layer/enabled: true,
  inflation_layer/enabled: true,
  # avoid eccessively conservative behaviors  
  robot_radius: 0.1,
  inflation_layer/inflation_radius: 0.6,
  inflation_layer/cost_scaling_factor: 2.5} 

#
# local_costmap_params.yaml ends here