# local_costmap_params.yaml --- 
# 
# Filename: local_costmap_params.yaml
# Description: Costmap parameters for LocalPlanner
# Created: Thu Feb 26 18:03:04 2015 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

local_costmap: {
  global_frame: /map,
  robot_base_frame: /base_link,
  update_frequency: 5.0,
  publish_frequency: 5.0,
  static_map: false,
  resolution: 0.05,
  map_layer/enabled: false,
  perception_layer/enabled: true,
} 

#
# local_costmap_params.yaml ends here
