# frames
map_frame: "/map"
odom_frame: "/odom"
robot_frame: "/base_link"

# initial pose
init_pose_x: 0.0
init_pose_y: 0.0
init_pose_a: 0.0

localizer:
  num_particles: 750
  min_lin_update: 0.1
  min_ang_update: 0.1
  init_stddev_x: 0.2
  init_stddev_y: 0.2
  init_stddev_a: 0.5

motion_model:
  noise_xx: 1.0
  noise_xy: 0.0
  noise_xa: 0.0
  noise_yy: 1.0
  noise_ya: 0.0
  noise_aa: 1.5
  noise_magnitude: 0.2

likelihood_field:
  saturation_distance: 0.5
  observation_sigma: 0.5

laser_model:
  beam_min_distance: 0.1

