LocalPlanner: 
  verbose: false
  goal_lin_tolerance: 0.05
  goal_ang_tolerance: 0.05
  max_safe_lin_velocity: 0.5
  max_safe_ang_velocity: 0.7
  max_safe_lin_displacement: 0.5
  max_safe_ang_displacement: 1.0
  
  MotionPlanner:
    max_linear_velocity: 0.5
    max_angular_velocity: 0.7
    linear_smoother: 0.95
    angular_smoother: 0.95
    time_scaler: 1.25
    waypoints_heading_lookahead: 10

  ControllerPID:
    kP_lin: 3.0
    kP_ang: 3.0
    kI_lin: 0.001
    kI_ang: 0.001
    kD_lin: 0.001
    kD_ang: 0.001