global_costmap: 
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  resolution: 0.05
  static_map: false
  map_layer/enabled: true
  obstacles_layer/enabled: true
  inflation_layer/enabled: true
