move_base:
  global_planner:
    robot_base_frame: "/base_linkz"
  local_planner:
    robot_base_frame: "/base_linkz"

squirrel_localizer:
  base_link_frame_ID: "/base_linkz"

squirrel_3d_localizer:
  base_frame_id: "/base_linkz"
  base_footpront_id: "/base_linkz"
