LocalPlanner: {
  verbose: false,
  max_linear_vel: 0.5,
  max_angular_vel: 0.7,
  xy_goal_tolerance: 0.10,
  yaw_goal_tolerance: 0.10,
  controller_gains/P_linear: 2.5,
  controller_gains/P_angular: 1.5,
  controller_gains/I_linear: 0.01,
  controller_gains/I_angular: 0.01,
  controller_gains/D_linear: 0.001,
  controller_gains/D_angular: 0.001,
}