# costmap_common_params.yaml --- 
# 
# Filename: costmap_common_params.yaml
# Description: Global parameters for layered costmap
# Created: Tue Nov 24 14:33:55 2015 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

# costmap_2d plugins declaration.
plugins:
  - {name: map_layer, type: "squirrel_navigation::MapLayer"}
  - {name: obstacles_layer, type: "squirrel_navigation::DownprojectionLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

map_layer:
  robot_link_radius: 0.22
  inflation_radius: 0.6
  cost_scaling_factor: 10.0

# Parameters for squirrel_navigation::ObstacleLayer
obstacles_layer:
  obstacle_range: 1.5
  raytrace_range: 3.0 
  observation_sources: laser_scan rgbd_scan
  rgbd_scan: {sensor_frame: kinect_depth_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: false}
  laser_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: true} 
  publish_voxel_map: true
  robot_height: 0.47
  floor_threshold: 0.04
  robot_diameter: 0.5

#
# costmap_common_params.yaml ends here
