robot_radius: 0.22

# costmap_2d plugins declaration.
plugins:
  - {name: map_layer, type: "costmap_2d::StaticLayer"}
  - {name: navigation_layer, type: "squirrel_navigation::NavigationLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

# Parameters for squirrel_navigation::DownprojectionLayer
navigation_layer:
  use_kinect: true
  use_laser_scan: true

  laser_layer:
    obtacle_range: 5.0
    raytrace_range: 10.0
    observation_sources: laser_scan
    laser_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
    publish_voxel_map: false

  kinect_layer:
    obstacle_range: 3.0
    raytrace_range: 10.0
    observation_sources: kinect_scan
    kinect_scan: {sensor_frame: kinect_depth_optical_frame, data_type: PointCloud2, topic: /rgbdscan, marking: true, clearing: true}
    publish_voxel_map: false
    robot_height: 0.9
    floor_threshold: 0.05

# Parameters for squirrel_navigation::InflationLayer
inflation_layer:
  inscribed_radius: 0.22
  inscribed_radius_from_footprint: false
  inflation_radius: 0.6,
  cost_scaling_factor: 10.0

#
# costmap_common_params.yaml ends here
