# global_costmap_params.yaml --- 
# 
# Filename: global_costmap_params.yaml
# Description: Costmap parameters for the global Planner (Dijkstra)
# Created: Tue Nov 24 14:33:45 2015 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

global_costmap: {
  global_frame: /map,
  robot_base_frame: /base_link,
  update_frequency: 5.0,
  publish_frequency: 5.0,
  resoltion: 0.025,
  static_map: false,
  map_layer/enabled: true,
  ostacles_layer/enabled: true,
  inflation_layer/enabled: true,
}

#
# global_costmap_params.yaml ends here
