move_base:
  global_costmap:
    robot_base_frame: "/base_link"
  local_costmap:
    robot_base_frame: "/base_link"

squirrel_localizer:
  base_link_frame_ID: "/base_link"

squirrel_3d_localizer:
  base_frame_id: "/base_link"
  base_footprint_id: "/base_link"

squirrel_3d_mapping:
  base_frame_id: "/base_link"